" Stolen wholesale from christoomey:
" https://github.com/christoomey/dotfiles/blob/master/vim/vimrc
function! s:SourceConfigFilesIn(directory)
  let directory_splat = '~/.vim/' . a:directory . '/*.vim'
  for config_file in split(glob(directory_splat), '\n')
    if filereadable(config_file)
      execute 'source' config_file
    endif
  endfor
endfunction

" Disable Vi compatibility
set nocompatible

" Map leader before other keymaps
let mapleader = "\<Space>"

" Source plugins
call plug#begin('~/.vim/plugged')
call s:SourceConfigFilesIn('plugins')
call plug#end()


" Colours!
syntax enable
set background=dark
set t_Co=256  " enable 256 colours
colorscheme solarized


" Spaces
set expandtab       " tabs are spaces
set tabstop=2       " number of visual spaces per tab char
set softtabstop=2   " number of spaces in tab when editing
set shiftwidth=2    " set shiftwidth so >> is 2 spaces


set number          " show line numbers
set relativenumber  " show line numbers relative to cursor
set showcmd         " show command in bottom bar
set cursorline      " highlight line cursor is on
set ruler           " always show cursor position
set laststatus=2    " always show a something bar
set incsearch       " show matching search results as typing
set ignorecase      " case insensitive search by default
set smartcase       " override ignorecase when term contains uppercase char
set autoindent      " copy the indentation from the previous line
set list            " show `listchars` characters
set scrolloff=3     " number of lines to always show at at the top & bottom
set hidden          " hide buffers rather than unloading then (so we don't
                    " have to save when switching buffers)
set wildmenu        " show available commands when autocompleting with tab
set wildmode=longest:full,full
set visualbell      " no beeping
set autoread        " reload file when changed on disk

set listchars=tab:=»,trail:·
set backspace=indent,eol,start   " make backspace behave in a sane manner

set splitright      " open vertical splits on the right
set splitbelow      " open the horizontal split below

set completeopt-=preview

" Make vim remember undos, even when the file is closed!
set undofile                              " save undo's after file closes
set undodir=~/.vim/tmp/undo//,/tmp//,.    " where to save undo histories
set undolevels=1000                       " how many undos
set undoreload=10000                      " number of lines to save for undo

" Keep backups and swap files in central location
set directory=$HOME/.vim/tmp/swap//,/tmp//,.
set backupdir=$HOME/.vim/tmp/backup//,/tmp//,.

" Improve vim's scrolling speed
set ttyfast
set ttyscroll=3
set lazyredraw

set linespace=0

" Trigger autoread when changing buffers or coming back to vim.
au FocusGained,BufEnter * :silent! !

" Key maps!!

" Quick escaping
inoremap jk <Esc>

" Select pasted text
nnoremap gp `[v`]

" Leader maps
nnoremap <leader>s :w<CR>
nnoremap <leader>q :q<CR>
nnoremap <leader>r :e!<CR>

" Copy all lines to system clipboard
nnoremap <leader>c :%y*<CR>

" Copy selected text to system clipboard
vnoremap <leader>y "*y

" vimrc
nnoremap <leader>vv :e $MYVIMRC<CR>
nnoremap <leader>vs :w<CR>:source $MYVIMRC<CR>
nnoremap <leader>vr :source $MYVIMRC<CR>
nnoremap <leader>vo <C-w><C-v><C-l>:e $MYVIMRC<cr>

" Tabs and buffers
nnoremap <leader>tn :tabnew<CR>
nnoremap <leader>tk :tabnext<CR>
nnoremap <leader>tj :tabprev<CR>
nnoremap <leader>tc :tabclose<CR>
nnoremap <leader>k :bn<CR>
nnoremap <leader>j :bp<CR>
nnoremap <leader>d :bd<CR>

" Switching between last buffer
nnoremap <tab> :b#<CR>

" Search for visually highlighted text
vnoremap // y/<C-R>"<CR>

" Disable search highlighting until next search
nnoremap <leader><space> :noh<CR>

" Toggle highlighting for searches (in normal mode)
nnoremap <F2> :set hls!<CR>
set hlsearch

" Open new vertical split and switch to it
nnoremap <leader>w <C-w>v<C-w>l

" Search for visually selected text
vnoremap // y/<C-R>"<CR>

" Make vim indent normal tags
:let g:html_indent_inctags = "html,body,head,tbody"
