# vim: syntax=ruby filetype=ruby

# https://robots.thoughtbot.com/brewfile-a-gemfile-but-for-homebrew
#
# To install from this file:
#   $ brew tap homebrew/bundle
#   $ brew bundle
#
# Make sure using latest Homebrew:
#   $ brew update
#
# Update already-installed brews:
#   $ brew upgrade
#
# Update already-installed casks:
#   $ brew cu

tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'homebrew/cask'
tap 'homebrew/cask-fonts'
tap 'homebrew/cask-versions'
tap 'buo/cask-upgrade'

brew 'coreutils'

# Shell utilities
brew 'asciinema'
brew 'bat'
brew 'cheat'
brew 'direnv'
brew 'exa'
brew 'fasd'
brew 'fd'
brew 'fpp'
brew 'fx'
brew 'gifsicle'
brew 'htop'
brew 'imagemagick'
brew 'ncdu'
brew 'ranger'
brew 'ripgrep'
brew 'tldr'
brew 'trash'
brew 'tree'

# Vim
brew 'neovim'
brew 'vim', args: ["HEAD"]

# Tmux
brew 'reattach-to-user-namespace'
brew 'tmux'

# Git
brew 'git'
# TODO: learn how to tweak colours so they're less ugly
brew 'git-delta'
brew 'tig'

# Node
brew 'yarn', args: ["ignore-dependencies"]

# Go
brew 'go'

# Docker
# TODO: script initial setup
brew 'docker'
brew 'docker-machine'

# Ruby
brew 'chruby'
brew 'ruby-install'
brew 'ruby'

# Python
brew 'python'

# MySQL
brew 'mysql'

# OSX
brew 'switchaudio-osx'

# CLI for Mac App Store
brew 'mas'

# Apps
cask '1password'
cask 'aerial'
cask 'alfred'
cask 'anki'
cask 'charles'
cask 'dash'
cask 'discord'
cask 'dropbox'
cask 'evernote'
cask 'firefox'
cask 'flux'
cask 'google-chrome'
cask 'google-chrome-canary'
cask 'hazel'
cask 'istat-menus'
cask 'karabiner-elements'
cask 'keepingyouawake'
cask 'kitty'
cask 'licecap'
cask 'marked'
cask 'mos'
cask 'notion'
cask 'postman'
cask 'quicklook-json'
cask 'rectangle'
cask 'rocket'
cask 'sketch'
cask 'slack'
cask 'spotify'
cask 'vanilla'
cask 'virtualbox'
cask 'visual-studio-code'
cask 'vlc'

# Fonts
cask 'font-fira-code'

# Mac App Store Apps
mas 'DaisyDisk', id: 411643860
mas 'Day One', id: 1055511498
mas 'GIF Keyboard', id: 1043270657
mas 'Gifski', id: 1351639930
mas 'Icon Slate', id: 439697913
mas 'Messenger', id: 1480068668
mas 'Noizio', id: 928871589
mas 'Sip', id: 507257563
mas 'Twitter', id: 1482454543
mas 'WhatsApp', id: 1147396723
mas 'Xcode', id: 497799835
