# vim: syntax=ruby filetype=ruby

# https://robots.thoughtbot.com/brewfile-a-gemfile-but-for-homebrew
#
# To install from this file:
#   $ brew tap homebrew/bundle
#   $ brew bundle
#
# Make sure using latest Homebrew:
#   $ brew update
#
# Update already-installed brews:
#   $ brew upgrade
#
# Update already-installed casks:
#   $ brew upgrade --cask

tap 'homebrew/bundle'
tap 'homebrew/cask-fonts'

brew 'coreutils'

# Shell utilities
brew 'asciinema'
brew 'bat'
brew 'cheat'
brew 'direnv'
brew 'eza'
brew 'fd'
brew 'fpp'
brew 'fx'
brew 'fzf'
brew 'gifsicle'
brew 'gpg'
brew 'htop'
brew 'imagemagick'
brew 'ncdu'
brew 'ranger'
brew 'ripgrep'
brew 'tldr'
brew 'trash'
brew 'zoxide'

# Vim
brew 'neovim'
brew 'tree-sitter'
brew 'vim'

# Tmux
brew 'reattach-to-user-namespace'
brew 'tmux'

# Git
brew 'git'
brew 'git-delta'
brew 'git-lfs'
brew 'lazygit'

# Go
brew 'go'

# Lua
brew 'lua'
brew 'luarocks'

# Docker
brew 'docker'

# Ruby
brew 'chruby'
brew 'ruby-install'
brew 'ruby'

# Python
brew 'python'

# MySQL
brew 'mysql'

# CLI for Mac App Store
brew 'mas'

# skhd for key bindings
# TODO: consider migrating to https://github.com/jackielii/skhd.zig
tap 'koekeishiya/formulae'
brew 'koekeishiya/formulae/skhd', args: ["HEAD"]

# Apps
cask '1password'
cask '1password-cli'
cask 'aerial'
cask 'aerospace'
cask 'alfred'
cask 'charles'
cask 'discord'
cask 'dropbox'
cask 'firefox'
cask 'google-chrome'
cask 'hammerspoon'
cask 'insomnia'
cask 'istat-menus'
cask 'keepingyouawake'
cask 'kitty'
cask 'marked-app'
cask 'mos'
cask 'notion'
cask 'obsidian'
cask 'postman'
cask 'rocket'
cask 'slack'
cask 'spotify'
cask 'visual-studio-code'
cask 'vlc'

# Fonts
cask 'font-fira-code'
cask 'font-fira-code-nerd-font'
cask 'font-hack-nerd-font'
cask 'font-jetbrains-mono-nerd-font'

# Mac App Store Apps
mas 'DaisyDisk', id: 411643860
mas 'Day One', id: 1055511498
mas 'Gifski', id: 1351639930
mas 'Messenger', id: 1480068668
mas 'Sip', id: 507257563
mas 'WhatsApp', id: 1147396723
mas 'Xcode', id: 497799835
