#!/bin/bash

# Header logging
e_header() {
  printf "\n$(tput setaf 7)$(tput bold)%s$(tput sgr0)\n" "$@"
}

# Step logging
e_step() {
  printf "$(tput setaf 8)› %s$(tput sgr0)\n" "$@"
}

# Success logging
e_success() {
  printf "$(tput setaf 64)✓ %s$(tput sgr0)\n" "$@"
}

# Warning logging
e_warning() {
  printf "$(tput setaf 136)! %s$(tput sgr0)\n" "$@"
}

# Error logging
e_error() {
  printf "$(tput setaf 1)x %s$(tput sgr0)\n" "$@"
}

# Ask for confirmation before proceeding
ask() {
  read -p $'\n\e[35m'"$@"$' (y/N)\e[0m: ' -n 1
  printf "\n"
}

# Test whether the result of an 'ask' is a confirmation
is_confirmed() {
  if [[ "$REPLY" =~ ^[Yy]$ ]]; then
    return 0
  fi
  return 1
}
