# vim:ft=kitty

## name:     Kanagawa Dragon
## author:   rebelot
## license:  MIT
## upstream: https://github.com/rebelot/kanagawa.nvim
## blurb:    Dark theme inspired by Katsushika Hokusai — Dragon variant

# The basic colors
foreground              #c5c9c5
background              #181616
selection_foreground    #c8c093
selection_background    #2d4f67

# Cursor colors
cursor                  #c8c093
cursor_text_color       #181616

# URL underline color when hovering with mouse
url_color               #658594

# Kitty window border colors
active_border_color     #c8c093
inactive_border_color   #393836
bell_border_color       #c4b28a

# OS Window titlebar colors
wayland_titlebar_color  system
macos_titlebar_color    system

# Tab bar colors
active_tab_foreground   #181616
active_tab_background   #c5c9c5
inactive_tab_foreground #a6a69c
inactive_tab_background #282727
tab_bar_background      #0d0c0c

# Colors for marks (marked text in the terminal)
mark1_foreground #181616
mark1_background #658594
mark2_foreground #181616
mark2_background #8992a7
mark3_foreground #181616
mark3_background #8ba4b0

# The 16 terminal colors

# black
color0  #0d0c0c
color8  #625e5a

# red
color1  #c4746e
color9  #c4746e

# green
color2  #8a9a7b
color10 #8a9a7b

# yellow
color3  #c4b28a
color11 #c4b28a

# blue
color4  #8ba4b0
color12 #8ba4b0

# magenta
color5  #a292a3
color13 #a292a3

# cyan
color6  #8ea4a2
color14 #8ea4a2

# white
color7  #c5c9c5
color15 #9e9b93
