#!/bin/bash

dotfiles="${HOME}/.dotfiles"
source "${dotfiles}/scripts/lib/utils"

brew_pls() {
  brew bundle --file="${dotfiles}/homebrew/$1"
}

# Install Xcode Command Line Tools...
if [[ $(command -v xcodebuild) == "" ]] ; then
  e_header "Installing command-line tools..."
  xcode-select --install
fi

# Install Homebrew
if [[ $(command -v brew) == "" ]] ; then
  e_header "Installing Homebrew..."
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

  # Set up Homebrew environment for current session
  if [[ $(uname -m) == "arm64" ]]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
  else
    eval "$(/usr/local/bin/brew shellenv)"
  fi

  brew analytics off

  e_header "Installing brews..."
  brew_pls "Brewfile"

  ask "Install home (non-work) applications?"
  if is_confirmed; then
    e_header "Installing home applications..."
    brew_pls "Brewfile.home"
  else
    printf "\n"
    e_step "Skipping home applications"
  fi

# Update Homebrew
else
  e_header "Updating Homebrew..."
  brew update

  e_header "Checking for outdated brews..."
  brew outdated
  e_warning "Run \`brew upgrade\` to upgrade everything"
  e_warning "Run \`brew upgrade <package_name>\` to upgrade specific packages"
fi

e_success "Homebrew setup complete!"
