#!/bin/bash

source "${HOME}/.dotfiles/scripts/lib/utils"

e_header "Creating scratch directories..."
mkdir -p ${HOME}/.local/share/nvim/{swap,backup,undo,view}

e_header "Installing vim-plug..."
if [ ! -f ~/.local/share/nvim/site/autoload/plug.vim ]; then
  curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

e_header "Installing Python prodivers..."
sudo pip2 install --upgrade pynvim
sudo pip3 install --upgrade pynvim

e_header "Installing Node provider..."
npm i -g neovim

# TODO: ensure ruby is properly installed by this point
e_header "Installing Ruby provider..."
gem install neovim

e_header "Installing Neovim plugins..."
nvim +PackerSync +qall

e_success "Neovim setup complete!"
