#!/bin/bash

source "${HOME}/.dotfiles/scripts/lib/utils"

e_header "Creating scratch directories..."
mkdir -p ${HOME}/.local/share/nvim/{swap,backup,undo}

e_header "Installing vim-plug..."
if [ ! -f ~/.local/share/nvim/site/autoload/plug.vim ]; then
  curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

e_header "Installing Neovim plugins..."
nvim +PlugInstall +qall

e_success "Neovim setup complete!"
