#!/bin/bash

source "${HOME}/.dotfiles/scripts/lib/utils"
source "${HOME}/.nvm/nvm.sh"

e_header "Setting up nvm, node and npm..."
if [[ $(command -v nvm) == "" ]] ; then
  e_error "nvm is not installed"
  e_error "Finish setting up zsh with \`scripts/setup-zsh\` before running this script"
  # zsh setup needs to happen because nvm is installed as a zsh plugin
else
  # Install latest LTS
  e_header "Installing latest LTS node..."
  nvm install --lts
  nvm alias default "lts/*"

  # Update npm
  e_header "Installing latest npm..."
  npm i -g npm

  # Set npm config
  e_header "Tweaking npm config..."
  npm config set depth 0

  # Install global node packages
  e_header "Installing global node packages..."
  packages=(
    asciicast2gif
    claude
    concurrently
    emoj
    eslint
    eslint-plugin-react
    http-server
    nodemon
    prettier
    typescript
  )
  npm i -g "${packages[@]}"

  e_success "Node setup complete!"
fi
