#!/usr/bin/env bash

# Sets some sensible defaults for OSX.
# Stolen liberally from mathiasbynens:
# https://mths.be/macos

source "${HOME}/.dotfiles/scripts/lib/utils"

# Close any open System Preferences panes, to prevent them from overriding
# settings we’re about to change
osascript -e 'tell application "System Preferences" to quit'

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until `.macos` has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# Loop through scripts in macos/ and run
e_header "Applying sensible MacOS settings..."
for file in $HOME/.dotfiles/scripts/macos/*; do
  e_step "Applying $file"
  bash $file
done
