#!/bin/zsh

# TODO: replace with zinit installation
# source $ZPLUG_HOME/init.zsh
source "${HOME}/.dotfiles/scripts/lib/utils"

# Exit if Homebrew isn't installed yet
if [[ $(command -v brew) == "" ]] ; then
  e_error "Homebrew isn't installed. Please run scripts/homebrew first!"
  exit 1
fi

# Detect Homebrew prefix if not already set
if [[ -z "$HOMEBREW_PREFIX" ]]; then
  if [[ $(uname -m) == "arm64" ]]; then
    HOMEBREW_PREFIX="/opt/homebrew"
  else
    HOMEBREW_PREFIX="/usr/local"
  fi
fi

# Install latest zsh
e_header "Installing latest zsh..."
brew install zsh

# Add homebrew zsh to whitelist
e_header "Adding homebrew zsh to /etc/shells whitelist..."
zsh_path="$HOMEBREW_PREFIX/bin/zsh"
if [[ $(grep "$zsh_path" /etc/shells) == "" ]]; then
  echo "$zsh_path" | sudo tee -a /etc/shells
  e_step "Added!"
else
  e_step "An entry already exists!"
fi

# Change shell to zsh
e_header "Changing default shell to zsh..."
new_shell="$HOMEBREW_PREFIX/bin/zsh"
chsh -s "$new_shell"

# Install zsh plugins
# TODO: replace with zinit plugin installation
# e_header "Installing zsh plugins..."
# zplug install

e_success "zsh setup complete!"
