#!/bin/bash

source "${HOME}/.dotfiles/scripts/lib/utils"

# Create/replace symlink
link() {
  src="${HOME}/.dotfiles/${1}"
  # If file/dir doesn't exist, exit
  if [[ -e "${src}" ]]; then
    ln -sfn "${src}" "${HOME}/${2}"
    e_step "Linked ~/${2}"
  else
    e_warning "File doesn't exist: ${src}"
  fi
}

e_header "Symlinking files..."

mkdir -p ${HOME}/.config/nvim

link "zsh/zshrc" ".zshrc"
link "zsh/zshenv" ".zshenv"
link "tmux/tmux.conf" ".tmux.conf"
link "vim/vimrc" ".config/init.vim"
link "vim/plugins" ".config/nvim/plugins"
link "vim/configs" ".config/nvim/configs"
link "git/gitconfig" ".gitconfig"
link "git/gitignore" ".gitignore"
link "ripgrep/ripgreprc" ".ripgreprc"
link "karabiner/karabiner.json" ".config/karabiner/karabiner.json"
link "spectacle/Shortcuts.json" "Library/Application Support/Spectacle/Shortcuts.json"

e_success "Symlinking complete!"
