#!/bin/bash

source "${HOME}/.dotfiles/scripts/lib/utils"

# Create/replace symlink
link() {
  src="${HOME}/.dotfiles/${1}"
  # If file/dir doesn't exist, exit
  if [[ -e "${src}" ]]; then
    ln -sfn "${src}" "${HOME}/${2}"
    e_step "Linked ~/${2}"
  else
    e_warning "File doesn't exist: ${src}"
  fi
}

e_header "Symlinking files..."

# Create dest dirs in case they don't exist
mkdir -p ${HOME}/.config/{nvim,kitty}

link "zsh/zshrc" ".zshrc"
link "zsh/zshenv" ".zshenv"
link "tmux/tmux.conf" ".tmux.conf"
link "nvim/init.lua" ".config/nvim/init.lua"
link "nvim/lua" ".config/nvim/lua"
link "nvim/snippets" ".config/nvim/snippets"
link "nvim/after" ".config/nvim/after"
link "skhd/skhdrc" ".config/skhd/skhdrc"
link "aerospace/aerospace.toml" ".config/aerospace/aerospace.toml"
link "git/gitconfig" ".gitconfig"
link "git/gitignore" ".gitignore"
link "ripgrep/ripgreprc" ".ripgreprc"
link "kitty/kitty.conf" ".config/kitty/kitty.conf"
link "kitty/themes" ".config/kitty/themes"
link "lazygit/config.yml" ".config/lazygit/config.yml"
link "hammerspoon/init.lua" ".hammerspoon/init.lua"

e_success "Symlinking complete!"
