#!/bin/bash

source "${HOME}/.dotfiles/scripts/lib/utils"

# Create/replace symlink
link() {
  src="${HOME}/.dotfiles/${1}"
  # If file/dir doesn't exist, exit
  if [[ -e "${src}" ]]; then
    ln -sfn "${src}" "${HOME}/${2}"
    e_step "Linked ~/${2}"
  else
    e_warning "File doesn't exist: ${src}"
  fi
}

e_header "Symlinking files..."

# Create dest dirs in case they don't exist
mkdir -p ${HOME}/.config/{nvim,kitty,karabiner}

link "zsh/zshrc" ".zshrc"
link "zsh/zshenv" ".zshenv"
link "tmux/tmux.conf" ".tmux.conf"
link "nvim/init.lua" ".config/nvim/init.lua"
link "nvim/lua" ".config/nvim/lua"
link "nvim/snippets" ".config/nvim/snippets"
link "git/gitconfig" ".gitconfig"
link "git/gitignore" ".gitignore"
link "ripgrep/ripgreprc" ".ripgreprc"
link "karabiner/karabiner.json" ".config/karabiner/karabiner.json"
link "kitty/kitty.conf" ".config/kitty/kitty.conf"

e_success "Symlinking complete!"
