export EDITOR=nvim

export RIPGREP_CONFIG_PATH="${HOME}/.ripgreprc"

export NVM_LAZY_LOAD=false
# export NVM_LAZY_LOAD_EXTRA_COMMANDS=('nvim')
# NOTE: setting NVM_LAZY_LOAD to true and adding nvim as a command slowsl down
# nvim startup time too much. Disabling nvm lazy load doesn't appear to have a
# noticeable impact on shell startup (it used to?).

export GOPATH=$HOME/go
export GOBIN=$GOPATH/bin

# Add homebrew binaries
export PATH="/usr/local/sbin:$PATH:${HOME}/.dotfiles/bin:$GOBIN"
