export EDITOR=nvim

export RIPGREP_CONFIG_PATH="${HOME}/.ripgreprc"

export GOPATH=$HOME/go
export GOBIN=$GOPATH/bin

# Add homebrew binaries
export PATH="/usr/local/sbin:$PATH:${HOME}/.dotfiles/bin:$GOBIN"
