# Assumes zplug is installed with homebrew
export ZPLUG_HOME=/usr/local/opt/zplug
source $ZPLUG_HOME/init.zsh

zplug 'mafredri/zsh-async', from:github
zplug 'sindresorhus/pure', use:pure.zsh, from:github, as:theme
zplug 'supercrabtree/k'
zplug 'zsh-users/zsh-syntax-highlighting', defer:2
zplug 'zsh-users/zsh-completions', defer:2

zplug load

# Source fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Source z
zpath="/usr/local/etc/profile.d/z.sh"
[ -f "$zpath" ] && source "$zpath"

# Source all zsh config files
for zsh_source in $HOME/.dotfiles/zsh/configs/*.zsh; do
  source $zsh_source
done
